merge without edits (doesn't work now)

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -2,7 +2,7 @@ name: Build furnace
 
 on:
   push:
-    branches: [master, esfm-contest]
+    branches: [master, powernoise]
   pull_request:
     branches: master
 
@@ -22,8 +22,8 @@ jobs:
           - { name: 'Windows MSVC x86_64', os: windows-latest, compiler: msvc, arch: x86_64 }
           #- { name: 'Windows MinGW x86', os: ubuntu-20.04, compiler: mingw, arch: x86 }
           #- { name: 'Windows MinGW x86_64', os: ubuntu-20.04, compiler: mingw, arch: x86_64 }
-          #- { name: 'macOS x86_64', os: macos-latest, arch: x86_64 }
-          #- { name: 'macOS ARM', os: macos-latest, arch: arm64 }
+          - { name: 'macOS x86_64', os: macos-latest, arch: x86_64 }
+          - { name: 'macOS ARM', os: macos-latest, arch: arm64 }
           - { name: 'Linux x86_64', os: ubuntu-20.04, arch: x86_64 }
           #- { name: 'Linux ARM', os: ubuntu-18.04, arch: armhf }
       fail-fast: false
@@ -284,15 +284,31 @@ jobs:
       if: ${{ runner.os == 'macOS' }}
       run: |
         pushd build
-        cpack
+        retries=0
+        while ! cpack; do
+          echo "TRYING AGAIN..."
+          retries=$((retries+1))
+          if [ $retries -gt 5 ]; then
+            echo "OH NO, WE'VE FAILED..."
+            exit 1
+            break
+          fi
+        done
 
+        echo "making dirs"
         mkdir orig
         mkdir new
+        echo "attaching"
         echo "y" | hdiutil attach Furnace-*-Darwin.dmg -readonly -mount required -mountpoint orig
 
+        echo "copying"
         cp -v -r orig/Furnace.app new/Furnace.app
+        echo "synchronizing"
+        sync
+        echo "detaching"
         hdiutil detach orig
 
+        echo "removing orig"
         rmdir orig
         rm Furnace-*-Darwin.dmg
 
@@ -301,6 +317,7 @@ jobs:
           rmdir new/Furnace.app/Contents/Resources/bin
         fi
 
+        echo "copying extra stuff"
         cp -v ../LICENSE new/LICENSE.txt
         cp -v ../res/releaseReadme/stable-mac.txt new/README
         cp -v -r ../demos new/demos
@@ -310,6 +327,7 @@ jobs:
         wget https://tildearrow.org/furnace/doc/latest/manual.pdf
         cd ..
 
+        echo "creating new image"
         hdiutil create -srcfolder new -volname Furnace -format UDZO furnace.dmg
         
         mv furnace.dmg ../${{ steps.package-identify.outputs.filename }}
